compute_environment: LOCAL_MACHINE
debug: false

distributed_type: FSDP
mixed_precision: bf16
downcast_bf16: "no"

num_machines: 1
num_processes: 2
machine_rank: 0
rdzv_backend: static
same_network: true

enable_cpu_affinity: false
use_cpu: false

main_training_function: main

fsdp_config:
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP


  fsdp_use_orig_params: true
  fsdp_sync_module_states: true


  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_offload_params: false

  fsdp_state_dict_type: SHARDED_STATE_DICT
