# ==========================================================
#  CDPAM Inference Configuration
# ==========================================================

model:
  name: "xls"
  device: "cuda"


# ----------------------------------------------------------
dataset:
  audio_dir: "audio"
  file_extension: ".wav"
  recursive: true
  sample_rate: 16000

# ----------------------------------------------------------
inference:
  batch_size: 4
  num_workers: 2
  prefetch_factor: 2
  output_dir: "./results/XLS"
  save_every_n_batches: 1
