# ==========================================================
#  CDPAM Inference Configuration
# ==========================================================

model:
  name: "cdpam"
  device: "cuda"
  checkpoint_path: null
  cdpam: {}

# ----------------------------------------------------------
dataset:
  audio_dir: "audio"
  file_extension: ".wav"
  recursive: true
  sample_rate: 16000
  max_length: 4

# ----------------------------------------------------------
inference:
  batch_size: 4
  num_workers: 2
  prefetch_factor: 2
  output_dir: "./results/cdpam"
  save_every_n_batches: 1
