# Configuration for DNSMOS model testing

# Model configuration
model:
  name: "dnsmos"
  device: "cuda"  # or "cpu"
  checkpoint_path: "bak_ovr.onnx" 
  segment_seed: 12345
  

    

dataset:
  audio_dir: "audio"
  file_extension: ".wav"
  recursive: true
  sample_rate: 16000
  max_length: 10                   # audio segment length in seconds


# Inference configuration
inference:
  batch_size: 1
  num_workers: 0
  output_dir: "./results/dnsmos"
  save_every_n_batches: 1
  prefetch_factor: 2
  experiment_name: "dnsmos_test"