# Configuration for DNSMOS model testing

# Model configuration
model:
  name: "dnsmos"
  device: "cuda"  # or "cpu"
  checkpoint_path: "bak_ovr.onnx" 
  

    

dataset:
  audio_dir: /home/maxim/MOS_research/tts_our
  file_extension: ".wav"
  recursive: true
  sample_rate: 16000                 # audio segment length in seconds


# Inference configuration
inference:
  batch_size: 1
  num_workers: 4
  output_dir: "./results/dnsmos/ttsbs1"
  save_every_n_batches: 1
  prefetch_factor: 2