# ==========================================================
#  NISQA Inference Configuration
#  Author: your_name
#  Description:
#    Configuration file for running non-intrusive speech quality
#    assessment (NISQA) using the NISQAWrapper model.
# ==========================================================

model:
  name: "nisqa"                 # Must match wrapper class name (NISQAWrapper)
  device: "cuda"                # "cuda" or "cpu"
  checkpoint_path: "nisqa_s.tar"
  config_path: "nisqa_s_np.yaml"



# ----------------------------------------------------------

dataset:
  audio_dir: /home/maxim/MOS_research/tts_our
  file_extension: ".wav"
  recursive: true
  # segment_seconds : 10
  sample_rate: 16000    

# ----------------------------------------------------------
inference:
  batch_size: 1                   # batch size (NISQA supports small batches)
  num_workers: 4                    # number of DataLoader workers
  prefetch_factor: 2                # optional for better throughput
  output_dir: "./results/nisqa/ttsbs1"     # where to save JSON/CSV results
  save_every_n_batches: 1         # how often to save partial results


