model:
  checkpoint: omniASR-W2V-300M.pt
  attentive_pooling: true
  type : '123'


training:
  epochs: 10
  batch_size: 8
  num_workers: 4
  lr: 1e-4
  weight_decay: 1e-5
  max_grad_norm: 1.0
  early_stop_patience: 10

accelerate:
  mixed_precision: bf16



data:
  train_csv: /home/maxim/MOS_research/train.csv
  val_csv: /home/maxim/MOS_research/val.csv


output:
  save_dir: ./checkpoints/omniASR/hf
