model:
  name: "proxymoshf"
  device: "cuda"
  proxymoshf:
          mixed_precision: "bf16" 


dataset:
  audio_dir: /home/maxim/MOS_research/tts_our
  recursive: true            
  sample_rate: 16000 

# ----------------------------------------------------------
inference:
  batch_size: 1
  num_workers: 4
  prefetch_factor: 2
  output_dir: "./results/proxymoshf/tts"
  save_every_n_batches: 1
  use_accelerator: true       
  memory_efficient: true      
  pin_memory: true  