

model:
  name: "wav2vec2"            
  device: "cuda"                
  checkpoint_path: null  


  torchaudiosslmos:
    model_type: "wav2vec2"      


# ----------------------------------------------------------

dataset:
  audio_dir: /home/maxim/MOS_research/tts_our
  file_extension: ".wav"
  recursive: true
  sample_rate: 16000
                     

# ----------------------------------------------------------
inference:
  batch_size: 1                
  num_workers: 4                  
  prefetch_factor: 2               
  output_dir: "./results/wav2vec2/ttsbs1"  
  save_every_n_batches: 1         
