model:
  name: "whisqa"                
  device: "cuda"               
  checkpoint_path: "multi_head_model.pt"  
  whisqa:
    mixed_precision: "bf16"
    compile: true        


  
# ---------------------------------------------------------
dataset:
  audio_dir: /home/maxim/MOS_research/urgent2024
  recursive: true
  sample_rate: 16000                 

# ----------------------------------------------------------
inference:
  batch_size:  1                # batch size
  num_workers: 2                    # number of DataLoader workers
  prefetch_factor: 2                # optional for better throughput
  output_dir: "./results/whisqa/urgent"    # where to save JSON/CSV results
  save_every_n_batches: 1         # how often to save partial results
